### PR TITLE
Update Dashboard to Correlate with Schema

### LINKED ISSUE #22: Server Crashes When Loading Dashboard
It probably has something to do with us redoing their schema and not updating the code to reflect those changes.

```
Magic happens on 8080
Database is connected
/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_NO_SUCH_TABLE: Table 'mkspostgres.UserEvents' doesn't exist
    at Query.Sequence._packetToError (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    --------------------
    at Protocol._enqueue (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/mysql/lib/Connection.js:201:25)
    at /Users/markcastle/Documents/Side Projects/open2/server/dashboard.js:69:6
    at Layer.handle [as handle_request] (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/express/lib/router/layer.js:95:5)
    at /Users/markcastle/Documents/Side Projects/open2/server/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/markcastle/Documents/Side Projects/open2/server/node_modules/express/lib/router/index.js:271:10)
```

### PR DESCRIPTION
**Pull request by mtham8**
Close #22

### CODE REVIEW

**Comment by merktassel** [comment]
Could you make these changes part of #23? They seem to be working together to accomplish the same thing. Just copy and paste the changes into the that branch and commit. Upon pushing the pull request should show the new commit.

**Comment by merktassel** [comment]
You typically want to close issues in the description of your pull request. Github doesn't recognize that syntax inside of pull request titles, so it won't have any affect other than making the pull requests harder to make sense of.

Other than that, great job! I'm glad we can finally start playing around with the dashboard.

**Comment by mtham8** [comment]
Not sure why my second commit is not showing ... I updated the schema in that commit -- 'Added creator column to attendance table', I pulled from master for the implement-branch and the schema change didn't show

**Comment by merktassel** [comment]
I'm not sure, but since the other pull request needed clarification I went ahead and merged this one by itself.

**Comment by mtham8** [comment]
Oh okay, sure, we'll figure it out tomorrow.

**Pull request merged**
